# Generated by Django 4.1.2 on 2022-12-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_booking_pnr_code_alter_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pnr_code',
            field=models.CharField(default='HSA3EL5A', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='O0UxwKw1Qd', max_length=10, unique=True),
        ),
    ]
