# Generated by Django 4.1.2 on 2022-12-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_profile_active_alter_booking_pnr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr_code',
            field=models.CharField(default='UIEIE07F', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='fvidjb5bx6', max_length=10, unique=True),
        ),
    ]
