# Generated by Django 4.1.2 on 2022-12-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_booking_pnr_code_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='fare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fare_boooking', to='core.fare'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='fare_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pnr_code',
            field=models.CharField(default='UAFF1BC2', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='lkRXrG45Eo', max_length=10, unique=True),
        ),
    ]
