# Generated by Django 4.1.2 on 2022-12-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_booking_fare_alter_booking_fare_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr_code',
            field=models.CharField(default='7VVGG60D', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='1QmbSGMXPU', max_length=10, unique=True),
        ),
    ]
