# Generated by Django 4.1.2 on 2022-12-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_booking_pnr_code_alter_payment_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='profille',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='booking',
            name='pnr_code',
            field=models.CharField(default='4BXQGBRC', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='ZhJdmR670R', max_length=10, unique=True),
        ),
    ]
