# Generated by Django 4.1.2 on 2023-02-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_profille_payment_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr_code',
            field=models.CharField(default='G4NEVHWG', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='H2IfSHGCDC', max_length=10, unique=True),
        ),
    ]
