# Generated by Django 4.1.2 on 2023-02-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_booking_pnr_code_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr_code',
            field=models.CharField(default='FZVAXOIP', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='DKPfAABzsd', max_length=10, unique=True),
        ),
    ]
