# Generated by Django 4.1.2 on 2023-02-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
